# Generated by Django 5.2.4 on 2025-07-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_contestapplication_contest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestapplication',
            name='contest_name',
        ),
        migrations.AlterField(
            model_name='contestapplication',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contests.contest'),
        ),
    ]
